---
title: "interactive life expectancy"
author: "SJ"
date: "4/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(readxl)
library(janitor)
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(leaps)
library(plotly)
```

```{r}
le <- read_excel("data/le mvw.xlsx")
```

# Scatter
```{r warning=FALSE}
fig = le %>%
    plot_ly(
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population,
    color = ~Continent, 
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~Year, 
    text = ~Country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  )

  
#mode=lines
fig <- fig %>% 
  layout( xaxis = list(type = "log"))%>%
  animation_button(x = 1, xanchor = "right", y = 0, yanchor = "bottom")%>%
   animation_opts(1000, easing='linear' , redraw = TRUE)
fig
```

# With Everything and line plot buth there are issues with line connecting
```{r warning=FALSE}
fig = le %>%
    plot_ly(
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    size = ~Population, 
    color = ~Continent, 
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~Year, 
    text = ~Country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines'
  )
#mode=lines
fig <- fig %>% 
  layout( xaxis = list(type = "log"))%>%
  animation_button(x = 1, xanchor = "right", y = 0, yanchor = "bottom")%>%
   animation_opts(1000, easing='linear' , redraw = TRUE)

fig
```

# Over time effect: Code is from plotly site
```{r}

accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}
```

```{r warning=FALSE}
library(quantmod)
```

# Issue with Split now generating too many legend labels
```{r warning=FALSE}
try <- le %>% accumulate_by(~Year)
fig = try %>%
    plot_ly(
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    size = ~Population, 
    split = ~Continent, 
    color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~Year, 
    text = ~Country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines'
  )
#mode=lines
fig <- fig %>% 
  layout( xaxis = list(type = "log"))%>%
  animation_button(x = 1, xanchor = "right", y = 0, yanchor = "bottom")%>%
   animation_opts(1000, easing='linear' , redraw = TRUE)

fig
```


```{r}
le1 = na.omit(le)
```


Note: This is the loooooong and painful way. I tried some looping but there are issues with it.
```{r warning=FALSE}
try <- le1 %>% accumulate_by(~Year)

fig = plot_ly(filter(mutate(try,names=rownames(try)),Country=="Algeria"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    color=~Continent,
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa"
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Angol"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Benin"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Botswana"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Burkina Faso"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Burundi"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Cameroon"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Angola"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Cape Verde"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Angola"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Central African Republic"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Chad"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Congo"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Comoros"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Cote d'Ivoire"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Djibouti"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Equatorial Guinea"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Egypt"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Eritrea"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Ethiopia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Gabon"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Gambia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Ghana"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Guinea"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Guinea-Bissau"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Kenya"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Liberia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Lesotho"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Libya"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Madagascar"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Malawi"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Mali"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Mauritania"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Mauritius"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Morocco"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Namibia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Mozambique"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Niger"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Nigeria"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Rwanda"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Sao Tome and Principe"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Senegal"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Seychelles"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Sierra Leone"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Somalia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="South Africa"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="South Sudan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Sudan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Tanzania"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Togo"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Tunisia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Uganda"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Zambia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Zimbabwe"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Africa",
    showlegend = FALSE
  )
fig
```


```{r}
fig1=fig%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Afghanistan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia"
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bahrain"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bangladesh"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bhutan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Brunei"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Cambodia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="China"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Hong Kong"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="India"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Indonesia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Iran"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Iraq"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Israel"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Japan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Jordan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Kazakhstan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Kuwait"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Laos"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Kyrgyzstan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Lebanon"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Malaysia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Maldives"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Mongolia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Myanmar"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Nepal"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Oman"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Pakistan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Philippines"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Qatar"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Saudi Arabia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Singapore"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Sri Lanka"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Syria"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Taiwan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Tajikistan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Thailand"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Tokelau"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Turkey"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Turkmenistan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="United Arab Emirates"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Uzbekistan"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Vietnam"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Western Sahara"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Yemen"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Asia",
    showlegend = FALSE
  )
```

```{r}
fig2=fig1%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Albania"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe"
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Andorra"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Armenia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Austria"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Belarus"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Belgium"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bosnia and Herzegovina"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bulgaria"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Croatia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Cyprus"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Denmark"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Estonia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Finland"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="France"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Georgia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Germany"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Gibraltar"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Greece"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Hungary"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Iceland"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Ireland"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Italy"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Latvia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Liechtenstein"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Ireland"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Lithuania"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Luxembourg"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Malta"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Moldova"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Monaco"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Montenegro"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Netherlands"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Norway"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Poland"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Portugal"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Romania"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="San Marino"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Slovakia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Serbia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Slovenia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Spain"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Sweden"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Switzerland"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Ukraine"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="United Kingdom"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Europe",
    showlegend = FALSE
  )
```

```{r}
fig3=fig2%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="American Samoa"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America"
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Anguilla"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Antigua and Barbuda"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Aruba"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bahamas"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Barbados"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Belize"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bermuda"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bonaire Sint Eustatius and Saba"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="British Virgin Islands"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Canada"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Cayman Islands"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Costa Rica"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Cuba"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Dominica"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Dominican Republic"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="El Salvador"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Greenland"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Grenada"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Guam"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Guatemala"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Haiti"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Honduras"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Jamaica"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Martinique"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Mexico"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Montserrat"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Nicaragua"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Panama"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Puerto Rico"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Saint Kitts and Nevis"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Saint Lucia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Saint Vincent and the Grenadines"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Trinidad and Tobago"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="United States"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="North America"
  )
```


```{r}
fig_All=fig3%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Australia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania"
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Fiji"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Kiribati"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Marshall Islands"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Mayotte"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Nauru"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="New Zealand"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Niue"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Palau"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Papua New Guinea"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Reunion"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Samoa"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Solomon Islands"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Tonga"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Tuvalu"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Vanuatu"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="Oceania",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Argentina"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America"
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Bolivia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Brazil"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Chile"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Colombia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Ecuador"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="French Guiana"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Guadeloupe"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Guyana"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="New Caledonia"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Paraguay"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Peru"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Suriname"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Uruguay"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )%>%
  add_trace(data=filter(mutate(try,names=rownames(try)),Country=="Venezuela"),
    x = ~`Male  Life Expectancy`, 
    y = ~`Female  Life Expectancy`, 
    #size = ~Population, 
    #split = ~Country,
    #color = ~Continent,
    colors = c("#a1d99b", "#fed976", "#969696", "#9ecae1", "#000000","#006d2c"),
    frame = ~frame, 
    text = ~text, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers+lines',
    legendgroup="South America",
    showlegend = FALSE
  )
```

```{r}
fig_All%>%
        layout(title = 'Life Expectancy by Sex for all Country', xaxis = list(title = 'Male Life EXpectancy'), 
         yaxis = list(title = 'Female Life EXpectancy'), legend = list(title=list(text='Geological Location')))
```

